const Liquid = require('liquid')

const Style = require('./shopify/style.js')
const EndStyle = require('./shopify/endstyle.js')
const Continue = require('./shopify/continue.js')
const Break = require('./shopify/break.js')
const Cycle = require('./shopify/cycle.js')
const TableRow = require('./shopify/tablerow.js')
const EndTableRow = require('./shopify/endtablerow.js')
const Form = require('./shopify/form.js')
const EndForm = require('./shopify/endform.js')
const Layout = require('./shopify/layout.js')
const Paginate = require('./shopify/paginate.js')
const EndPaginate = require('./shopify/endpaginate.js')
const Render = require('./shopify/render.js')
const LiquidLineTag = require('./shopify/liquid.js')
const Echo = require('./shopify/echo.js')

module.exports = {
  register: (engine) => {
    engine.registerTag('style', Style)
    engine.registerTag('endstyle', EndStyle)
    engine.registerTag('continue', Continue)
    engine.registerTag('break', Break)
    engine.registerTag('cycle', Cycle)
    engine.registerTag('tablerow', TableRow)
    engine.registerTag('endtablerow', EndTableRow)
    engine.registerTag('form', Form)
    engine.registerTag('endform', EndForm)
    engine.registerTag('layout', Layout)
    engine.registerTag('paginate', Paginate)
    engine.registerTag('endpaginate', EndPaginate)
    engine.registerTag('render', Render)
    engine.registerTag('liquid', LiquidLineTag)
    engine.registerTag('echo', Echo)
  }
}
