const Liquid = require('liquid')

const Style = require('./shopify/style.js')
const Continue = require('./shopify/continue.js')
const Break = require('./shopify/break.js')
const Cycle = require('./shopify/cycle.js')
const TableRow = require('./shopify/tablerow.js')
const Form = require('./shopify/form.js')
const Layout = require('./shopify/layout.js')
const Paginate = require('./shopify/paginate.js')
const Render = require('./shopify/render.js')
const LiquidLineTag = require('./shopify/liquid.js')
const Echo = require('./shopify/echo.js')
const EndCase = require('./shopify/endcase.js')
const EndFor = require('./shopify/endfor.js')
const EndIf = require('./shopify/endif.js')
const Section = require('./shopify/section.js')
const EndSection = require('./shopify/endsection.js')
const Schema = require('./shopify/schema.js')
const When = require('./shopify/when.js')
const Or = require('./shopify/or.js')

module.exports = {
  register: (engine) => {
    engine.registerTag('style', Style)
    engine.registerTag('continue', Continue)
    engine.registerTag('break', Break)
    engine.registerTag('cycle', Cycle)
    engine.registerTag('tablerow', TableRow)
    engine.registerTag('form', Form)
    engine.registerTag('layout', Layout)
    engine.registerTag('paginate', Paginate)
    engine.registerTag('render', Render)
    engine.registerTag('liquid', LiquidLineTag)
    engine.registerTag('echo', Echo)
    engine.registerTag('section', Section)
    engine.registerTag('endsection', EndSection)
    engine.registerTag('schema', Schema)
    engine.registerTag('endif', EndIf)
    engine.registerTag('endfor', EndFor)
    engine.registerTag('endcase', EndCase)
    engine.registerTag('when', When)
    engine.registerTag('or', When)
  }
}
